<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9w6s6lq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9w6s6lq/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9w6s6lq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9w6s6lq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9w6s6lq\appProdProjectContainer([
    'container.build_hash' => '9w6s6lq',
    'container.build_id' => '6f29c8fb',
    'container.build_time' => 1633288391,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9w6s6lq');
