<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWpxsggx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWpxsggx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWpxsggx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWpxsggx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWpxsggx\appDevDebugProjectContainer([
    'container.build_hash' => 'Wpxsggx',
    'container.build_id' => '5210d646',
    'container.build_time' => 1633295317,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWpxsggx');
